### ISSUE TITLE
Send directories?

### ISSUE THREAD

**Issue by nthiery** [tavinus/cloudsend.sh#1]
Thanks so much for cloudsend! It arrives just on time for my needs :-)

Would it be possible to send (recursively) a directory instead of a single file?
Probably not: I did not even manage to do it from the file-drop web page.

**Comment by tavinus** [comment]
Sending directories is currently not supported.  
  
You would have to make a script that will iterate through the files and send each one on its call.  
  
Also, cloudsend had no MakeDir call. [CloudManager](https://github.com/tavinus/cloudmanager) has makedir, but is not for sending files to public shares and also does not currently support sending folders.

**Comment by nthiery** [comment]
> Sending directories is currently not supported.  
>   
> You would have to make a script that will iterate through the files and send each one on its call.  
>   
> Also, cloudsend had no MakeDir call. CloudManager has makedir, but is not for sending files to public shares and also does not currently support sending folders.

Thanks much for the insight! Sending an archive file instead will be
slightly less convenient but will work too.

**Comment by tavinus** [comment]
Yep. You can tar/zip the folder and send it as well.  
  
Apart from that we would need to send all files, one by one anyways, even if I would implement it here.  
  
And there is no support to creating folders at the destination (all files would be sent to the shared folder root). I don't think I can do anything about that.

**Comment by tavinus** [comment]
Hi. I have [released a new version](https://github.com/tavinus/cloudsend.sh/releases) (2.1.0) which can both send multiple files (using globs) and also send piped content (using `-` OR `.` as input file name).  

---

**Here are the release notes:**
 - [x] Adds stdin as input option (piped content)
      - uses either `-` or `.` as input file name
      - requires `-r <filename>`
 - [x] Allows to use globbing at the input
      - can send multiple files by using globs
      - requires `-g` option
      - not compatible with `-r <name>` option (rename)
 - [x] Adds new checks and parsing
 - [x] Cleaned up unused code
 - [x] Updated readme and `--help`

[There is more info on the main Readme file](https://github.com/tavinus/cloudsend.sh).

**Comment by tavinus** [comment]
I have updated the readme with an example on how to send an entire folder (and/or subfolders) using `find` + `cloudsend`.  
  
**Folder send with `find` example:**
```
find ./ -maxdepth 1 -type f -exec ./cloudsend.sh {} https://cloud.mydomain.tld/s/TxWdsNX2Ln3X5kxG -p yourPassword \;
```
*This sends everything on the current shell folder.*
 - change the first `./` to change the input folder (eg. '/home/myname/myfolder')
 - `-maxdepth 1` will read current folder only, more levels go deeper, supressing goes all levels.

**Comment by nthiery** [comment]
Thanks! I just tried the `find` way. It has one caveat though: the directory structure is flattened.

**Comment by tavinus** [comment]
Yep, there is no way to create sub-folders.  
  
If you want to keep the tree, it would be better to send a zip or tarball.

**Comment by tavinus** [comment]
Like mentioned, we cannot create folders into shared links, so need to flatten or send a zip/tarball.  
  
After more than 2 months I will guess this is solved.  
Feel free to post again or reopen if the problem persists.

**Comment by tavinus** [comment]
Hi @nthiery  
  
v2.2.0 is out and is the first version that can send folders.
  
This one will actually create the whole tree and send everything.  
  
https://github.com/tavinus/cloudsend.sh/releases/

Cheers!

**Comment by nthiery** [comment]
Nice! Thank you for the update :-)

On Fri, Apr 30, 2021 at 09:16:16PM -0700, Gustavo Arnosti Neves wrote:
> Hi @nthiery  
>   
> v2.2.0 is out and is the first version that can send folders.
>   
> This one will actually create the whole tree and send everything.  
>   
> https://github.com/tavinus/cloudsend.sh/releases/

		Nicolas
--
Nicolas M. Thiéry "Isil" ***@***.***>
http://Nicolas.Thiery.name/

**Comment by tavinus** [comment]
Just pushed v2.2.1 with some fixes to the log messages.

Cheers
