### ISSUE TITLE
RPM package for ROSA

### ISSUE THREAD

**Issue by mikhailnov** [tavinus/cloudsend.sh#10]
Hello!
I have packaged your script into an RPM package, it is now in the contrib repository of ROSA Linux rosa2021.1
https://abf.io/import/cloudsend.sh
It can be installed on ROSA as `dnf install cloudsend.sh` or `dnf install cloudsend`.
An RPM can be downloaded from https://abf-downloads.rosalinux.ru/rosa2021.1/repository/x86_64/contrib/release/ and can be installed on other RPM-based distros.
Writing about it just to make you know about it.
Thanks for making this simple, but very useful script! I myself use it for [sberdisk.ru](https://sberdisk.ru) (something like a SaaS NextCloud).

**Comment by tavinus** [comment]
That is interesting. Thanks for letting me know. 👍

**Comment by tavinus** [comment]
New version available if you want to repack.  
  
Fixes for:
 - Files and folders with '#' in their names
 - Sending to a subfolder of the shared folder
