### ISSUE TITLE
Transfer of files/directories with # in name does not work

### ISSUE THREAD

**Issue by apachler** [tavinus/cloudsend.sh#11]
If the name of files or directories contain a hashtag (#) the transfer is not working and is reporting that the resource already exists.

**Comment by tavinus** [comment]
I would need more information to be sure, but I would guess that you are not "escaping" the hashtag. In Bash (and other shells) the # symbol is used for text comments. Meaning the interpreter will ignore anything after the # until the end of the line. So, if you really have a file name with a #, you will need to either quote `'#myfile'` or escape with a backslash `\#myfile.`

**Examples**
Creating a file fails without escaping
```
$ touch #myfile
touch: missing file operand
Try 'touch --help' for more information.
```
It works if quoting or escaping
```
$ touch '#myfile'
$ touch "#myfile2"
$ touch \#myfile3

$ ls -1
'#myfile'
'#myfile2'
'#myfile3'
```
**To use the files, the same rules applies.**  
  
It does not seem to be a problem when the # is not at the beginning of the file name. It will be a problem if it has a space before it though.
```
$ touch my#file
$ touch myfile#

$ ls -1
my#file
myfile#
```
The space breaks file name and makes the # start a comment
```
$ touch my #file

$ ls -1
my
```
Quoted / Escaped
```
$ touch 'my #file2'
$ touch my\ #file3 

$ ls -1
'my #file2'
'my #file3'
```

If I had your calls I would be able to know for sure if this is the case. This is my best guess anyways...

**Comment by apachler** [comment]
I am familiar with shell escaping, that is not the problem here ...

What i am using is the folder sync function (https://github.com/tavinus/cloudsend.sh#sending-entire-folder) of you tool.
If the name of a sub folder or file inside the folder consists of a # - the transfer is not working for those files/folders.

**Comment by tavinus** [comment]
Do you have any logs from the execution? Can you provide an example of a folder structure that fails?

**Comment by tavinus** [comment]
@apachler - Can you pls try version 2.2.2 and confirm it fixes your problem?
