### ISSUE TITLE
Get curl --limit-rate settings accessible

### ISSUE THREAD

**Issue by mate1213** [tavinus/cloudsend.sh#13]

**Comment by mate1213** [comment]
Hi!
I would like to use this script in automated enviroment. And in my case I need to limit the upload speed to do not disrupt other processes. (To set lower prio or higher nice value not na option sadly, and there is no effect on network usage.)
Best regards
Máté

**Comment by tavinus** [comment]
There is a new release with this option there v2.2.6
https://github.com/tavinus/cloudsend.sh/releases

Cheers!

**Comment by mate1213** [comment]
Thank you very much!
