### ISSUE TITLE
Support chunked upload

### ISSUE THREAD

**Issue by le-ander** [tavinus/cloudsend.sh#14]
Thanks so much for this amazing tool. As I'm using a commercially hosted nextcloud instance which means, I cannot upload files bigger than 10GB. I was wondering if you would be willing to support chunked uploading as described here: https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/chunking.html

**Comment by tavinus** [comment]
This is interesting, but I am not sure this is possible for shared folders.  
  
The document says "The API is only available for registered users of your instance". Which makes me think it would not work on shared folders. We could test anyways. **EDIT:** Gave another read and seems like we are out of luck to use their API. Even the Webdav URL is different and REQUIRES a user name.
  
If it does not work without a registered account, this could be added to my cloudmanager app. I wanted to change cloudmanager's account config for some time (I hate having 2 files there). I should also enable parameter login (to use without a config file). Maybe I can do all that and add this functionality as well. But takes some time and I also need scripts that would transform the old config into the new design.  
  
One option that is always available is to generate the chunks ourselves before sending them. But then I am not sure the "move/join" command would work (could be tested). This would also require extra space and processing in the origin to generate the chunks before sending them, unless we can find a way to split those files as we send them (on-the-fly).  
  
I have been quite busy with other things, but I will try to squeeze some time to study this. Any help is appreciated.

**EDIT2:** I am still not sure how this works, specially how to upload the chunks. The documentation uses `@chunk1,2,3` as the file to upload, so how does it even know what file it is sending? My guess is that we have to split the file before sending anyways. Yep, we need to use `split` and generate the chunks. To join, they use a `.file` which is probably created by the API (not sure). So we will need to also replicate that file to make the join work. Which means that the first step is to actually make this work manually, so we can inspect the files created and try to to the same stuff the API does.

**Comment by tavinus** [comment]
Hi.

Just made a few tries and it really does not work.  
  
When trying to upload a chunk, I get this error
```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotImplemented</s:exception>
  <s:message>There was no plugin in the system that was willing to handle this POST method.</s:message>
</d:error>
```

However, this is more like a utility helper.  

You could just run `split` in your files before sending them and then join them with `cat` in the remote server. You would need to ssh into the server, but at least it is possible. Maybe someone can create a plugin for Nextcloud to join files as well.  

I am closing this now, since it really is not possible at this point.
