### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by fastman** [tavinus/cloudsend.sh#4]
What do you think about adding a progress bar like `-#` with `|tee /dev/null` (like here: https://stackoverflow.com/a/41860083)?

**Comment by tavinus** [comment]
Hi.  
  
I have published a new release with the progress bar.  
  
https://github.com/tavinus/cloudsend.sh/releases  
  
Let me know if it works for ya.  
Cheers!  

  
## Release notes
Shows `curl --progress-bar` when not running in quiet mode.  
  
***NOTE:*** **Depending on the file size and the speed of the upload, it will be so fast that no upload progress bar will be shown. In these cases you will end up seeing only the connection bar running and then it will be over.**
  
Had to fix `$COLUMNS` detection which was causing the progress bar to span multiple lines in some systems.  
Now using the current screen columns - 1 (detected before running curl using `stty`).  
Default `$COLUMNS` size is `80`.  
  
You can create a big blank test file with something like
```
$ dd if=/dev/zero of=testfile.txt count=100 bs=1048576
```
*(this is for a 100MB file)*  
  
Then you can test sending it
```
$ ./cloudsend.sh ./testfile.txt https://cloud.my.site.com/index.php/s/e3FK2P1y4ghC7pd
```

**Comment by fastman** [comment]
Works great! Thanks!
