### ISSUE TITLE
Create folders

### ISSUE THREAD

**Issue by MuellerSeb** [tavinus/cloudsend.sh#7]
Thanks for this great tool!

Following your guide to upload whole folders, I was wondering if it is also possible to preserve the folder tree structure?

It is possible to create folders in the web-interface for a shared link. When a folder is present, one can add it to the url: `.../public.php/webdav/folder/bla.txt`. But putting `folder` in there without it being present results in an error:

```bash
  <s:message>File with name folder could not be located</s:message>
```

Is there a way to create folders on the fly?

Cheers,
Sebastian

**Comment by MuellerSeb** [comment]
Maybe with:
```bash
curl -X MKCOL
```
That is also done by pyocclient:
https://github.com/owncloud/pyocclient/blob/72a6666d7b9d022b5ee573a9d2568a0547823351/owncloud/owncloud.py#L702

**Comment by tavinus** [comment]
Hi. Thanks for the info.  
  
Something like this seems to work:
```
/usr/bin/curl -X MKCOL -u '2hsB1zw2q4frZsg:' -H 'X-Requested-With: XMLHttpRequest' 'https://cloud.mydomain.tld/public.php/webdav/TESTFOLDERNAME'
```

This opens the possibility to send the tree, but we still need to iterate through each file and subfolder, creating each folder and sending each file to its destination. This needs to traverse the whole tree, making a curl call to each item (file/folder).  
  
I am still checking if I can make curl do the hard lifting, it is not looking good though.  
  
My [cloudmanager](https://github.com/tavinus/cloudmanager) program also has this as a pending problem (sending entire folders).    
  
I tried using `curl --ftp-create-dirs` with `find`, but that does not seem to work in this case. ( [Reference](https://stackoverflow.com/questions/14019890/uploading-all-of-files-in-my-local-directory-with-curl) )  
  
I think the proper way would be to have 2 recursive functions. The first would traverse all subfolders and create them at the target, while the second would traverse all files and send them, each to its proper subfolder.  
  
We can probably just make 2 calls with `find -exec curl` (one for folders, one for files).  
I will keep testing...

**Edit:** I am implementing it. It is a bit complex, so it will take a bit of time. Also, I will probably need `readlink -f`, which is not present in MacOS/BSD systems. I have a bash implementation of it in my [pdfScale](https://github.com/tavinus/pdfScale) app. Seems like I will need it only when the current folder is passed to be sent, so I may be able to use `PWD` / `$pwd` instead. Seems like it will work, currently it already creates all the folders, but I still need to add a lot of error checkings and change the behaviour of older things. Also, it may be a bit slow to send a large tree and I am still figuring out how to log all of that to screen, if I should list all and ask before sending, etc, etc.

**Comment by tavinus** [comment]
I have it almost done.  
  
It is fully working already.  
  
Just cleaning up, making some more tests, fixing messages and some other minor things.  
  
The `curl --progress-bar` ["Spaceship Bar"](https://daniel.haxx.se/blog/2018/01/22/a-flying-curl-progress-bar/) span multiple lines in some systems, which was quite the pain to debug. I ended up fixing the BAR in a maximum of 80 Columns and that seems to solve the problem. This is not a critical bug, but it totally breaks the output when it happens.

Things like
![image](https://user-images.githubusercontent.com/8039413/116766498-36710d80-aa01-11eb-9c2c-099ea60bf415.png)

The same thing would happen when calling curl directly.  
  
This should have been fixed here: https://github.com/curl/curl/issues/4849  
It will probably take some time until it reaches most OSes, so I will keep it like this.  
  
This is how it is working at this moment
![image](https://user-images.githubusercontent.com/8039413/116766734-6a98fe00-aa02-11eb-9553-de06c39e3d0e.png)
  
It first creates all folders and then sends all files. The folder calls do not use curl's progress-bar (thank god), It just prints OK when Done or the error message from the XML (may need to refine for curl errors as well). The file sending part will display curl's progress-bar for each file.  
  
This is how it looks like if the folders already exists.
![image](https://user-images.githubusercontent.com/8039413/116766966-ad0f0a80-aa03-11eb-91ac-955d81b73ef3.png)
  
It will overwrite existing files as it does in a single file send.  
  
I will be pushing it soon...

**Comment by tavinus** [comment]
Hey @MuellerSeb ,
  
v2.2.0 is out and is the first version that can send folders.  
   
https://github.com/tavinus/cloudsend.sh/releases/  
  
Can you test it for me please?  
  
Cheers!

**Comment by tavinus** [comment]
Just pushed v2.2.1 with some fixes to the log messages.

Cheers

**Comment by tavinus** [comment]
Hi. It's been a couple of months without reply, so I will close this.  
Feel free to post again or reopen if needed.  
  
Cheers!
Gus
